services:
  expensecontrol-postgres:
    image: postgres:16
    container_name: expensecontrol-postgres
    environment:
      - POSTGRES_DB=ExpenseControlDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ExpenseControl123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - expensecontrol-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ExpenseControlDb -h localhost || exit 1; psql -U postgres -d ExpenseControlDb -c 'SELECT 1;' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  api:
    build:
      context: .
      dockerfile: ./ExpenseControl.Api/docker/Dockerfile
    container_name: expensecontrol-api
    ports:
      - "5293:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      expensecontrol-postgres:
        condition: service_healthy
    networks:
      - expensecontrol-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 5s
      retries: 10
  prometheus:
    image: prom/prometheus:latest
    container_name: expensecontrol-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./ExpenseControl.Api/Configuration/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - expensecontrol-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    container_name: expensecontrol-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=ExpenseControl123!
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - expensecontrol-network
    depends_on:
      - prometheus

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  expensecontrol-network:
    driver: bridge