// <auto-generated />
using System;
using ExpenseControl.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseControl.Api.Migrations
{
    [DbContext(typeof(ExpenseDbContext))]
    [Migration("20260206095711_AddHouseholdSupport")]
    partial class AddHouseholdSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseControl.Api.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("CategoryId", "Month", "Year", "HouseholdId")
                        .IsUnique();

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("ExpenseControl.Api.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Type")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a48cde78-354e-4d5c-9159-cf28368fcaca"),
                            Description = "Rent, mortgage, repairs, etc.",
                            IconName = "house",
                            Name = "Housing",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("eb318b9d-aafc-421d-8041-64c6889ffc3c"),
                            Description = "Car, public transit, fuel, etc.",
                            IconName = "car-front",
                            Name = "Transportation",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("c7e8d65f-f4b2-4162-ba57-04f52fb16d51"),
                            Description = "Groceries, dining out, etc.",
                            IconName = "cart",
                            Name = "Food",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("ac800e65-9ae2-4274-8c8a-ae4658345c99"),
                            Description = "Electricity, water, internet, etc.",
                            IconName = "lightning",
                            Name = "Utilities",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("92974cbf-e03c-4f33-9e36-9f9f0a97523e"),
                            Description = "Medical expenses, insurance, etc.",
                            IconName = "heart-pulse",
                            Name = "Healthcare",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("3feb665e-56c5-4251-bda6-d665dbda65d3"),
                            Description = "Regular employment income",
                            IconName = "wallet2",
                            Name = "Salary",
                            Type = "Income"
                        },
                        new
                        {
                            Id = new Guid("51630c3e-35be-4b55-87a9-68ef640f772c"),
                            Description = "Independent contractor income",
                            IconName = "briefcase",
                            Name = "Freelance",
                            Type = "Income"
                        },
                        new
                        {
                            Id = new Guid("683eba8b-531b-465e-8be4-584e85abdfb8"),
                            Description = "Dividends, interest, capital gains",
                            IconName = "graph-up-arrow",
                            Name = "Investments",
                            Type = "Income"
                        });
                });

            modelBuilder.Entity("ExpenseControl.Api.Entities.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("ExpenseControl.Api.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ExpenseControl.Api.Entities.Budget", b =>
                {
                    b.HasOne("ExpenseControl.Api.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseControl.Api.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("ExpenseControl.Api.Entities.Transaction", b =>
                {
                    b.HasOne("ExpenseControl.Api.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseControl.Api.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Household");
                });
#pragma warning restore 612, 618
        }
    }
}
