// <auto-generated />
using System;
using ExpenseControl.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseControl.Api.Migrations
{
    [DbContext(typeof(ExpenseDbContext))]
    [Migration("20250620130357_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseControl.Api.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Type")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0802a65-3cfb-47fd-bbd3-b18cb1c79f50"),
                            ColorCode = "#FF8C00",
                            Description = "Rent, mortgage, repairs, etc.",
                            IconName = "home",
                            Name = "Housing",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("d70fd34e-eac3-4f1e-a96d-7edc8173beda"),
                            ColorCode = "#4169E1",
                            Description = "Car, public transit, fuel, etc.",
                            IconName = "car",
                            Name = "Transportation",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("6bccc921-a2f2-4a81-b162-aa71e9dc64cb"),
                            ColorCode = "#32CD32",
                            Description = "Groceries, dining out, etc.",
                            IconName = "food",
                            Name = "Food",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("8b307833-0802-4a50-990a-acd0df4f95db"),
                            ColorCode = "#FFD700",
                            Description = "Electricity, water, internet, etc.",
                            IconName = "bolt",
                            Name = "Utilities",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("e1cb705a-05ff-440a-aae1-33242e9689a4"),
                            ColorCode = "#FF69B4",
                            Description = "Medical expenses, insurance, etc.",
                            IconName = "medical",
                            Name = "Healthcare",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("cdcdadce-8f78-4c89-ac76-ea6e837dc7f1"),
                            ColorCode = "#228B22",
                            Description = "Regular employment income",
                            IconName = "wallet",
                            Name = "Salary",
                            Type = "Income"
                        },
                        new
                        {
                            Id = new Guid("c7551968-2c51-427d-a4f1-80ce3a4e6347"),
                            ColorCode = "#4682B4",
                            Description = "Independent contractor income",
                            IconName = "briefcase",
                            Name = "Freelance",
                            Type = "Income"
                        },
                        new
                        {
                            Id = new Guid("e2da5652-4a3d-45db-8a59-7dd7c249f92e"),
                            ColorCode = "#9370DB",
                            Description = "Dividends, interest, capital gains",
                            IconName = "chart-line",
                            Name = "Investments",
                            Type = "Income"
                        });
                });

            modelBuilder.Entity("ExpenseControl.Api.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ExpenseControl.Api.Entities.Transaction", b =>
                {
                    b.HasOne("ExpenseControl.Api.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
