// <auto-generated />
using System;
using ExpenseControl.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseControl.Api.Migrations
{
    [DbContext(typeof(ExpenseDbContext))]
    [Migration("20250626205511_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseControl.Api.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Type")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09860853-4c8d-45af-b2f8-c13252feeb28"),
                            Description = "Rent, mortgage, repairs, etc.",
                            IconName = "house",
                            Name = "Housing",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("788cf435-f6f7-4bee-8954-e8f5a42bb4a6"),
                            Description = "Car, public transit, fuel, etc.",
                            IconName = "car-front",
                            Name = "Transportation",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("b5f100f7-990c-4dbb-8a49-9868b4694d4d"),
                            Description = "Groceries, dining out, etc.",
                            IconName = "cart",
                            Name = "Food",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("eaba9ca2-c6c8-4fb2-85a7-3b31813cc8f9"),
                            Description = "Electricity, water, internet, etc.",
                            IconName = "lightning",
                            Name = "Utilities",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("a62e5b4c-2202-4dea-892c-bc439d5041c3"),
                            Description = "Medical expenses, insurance, etc.",
                            IconName = "heart-pulse",
                            Name = "Healthcare",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("6129f445-8088-413c-a11f-c5ea70820e73"),
                            Description = "Regular employment income",
                            IconName = "wallet2",
                            Name = "Salary",
                            Type = "Income"
                        },
                        new
                        {
                            Id = new Guid("f841ed1c-0548-4a73-aaf2-25f274d8d603"),
                            Description = "Independent contractor income",
                            IconName = "briefcase",
                            Name = "Freelance",
                            Type = "Income"
                        },
                        new
                        {
                            Id = new Guid("f8af4340-31b2-4a7f-9f11-f08e3ed760ce"),
                            Description = "Dividends, interest, capital gains",
                            IconName = "graph-up-arrow",
                            Name = "Investments",
                            Type = "Income"
                        });
                });

            modelBuilder.Entity("ExpenseControl.Api.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ExpenseControl.Api.Entities.Transaction", b =>
                {
                    b.HasOne("ExpenseControl.Api.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
